### ISSUE TITLE
VSCode plugin displays "running" in status bar even after task has finished executing

### ISSUE THREAD

**Issue by Collect-diamond** [anish000kumar/easy-npm-support#2]
- 1.I have noticed that when I run a command using a certain VSCode plugin, the status bar at the bottom of the VSCode window shows "running". However, even after the task has finished executing, the status bar still displays "running". 

- 2.vscode terminal still exists after task finished, it would be better if terminal can auto closed after task finished

**Comment by anish000kumar** [comment]
Point1 seems like a bug, let me look into that.

For Point2, closing the terminal automatically may not be ideal. Folks usually want to see the output after executing a command. Example say I run ‘npm run test’, automatically closing the terminal would mean I can’t see test results once it’s done.

**Comment by anish000kumar** [comment]
Should be resolved in latest version.
