### ISSUE TITLE
Not finding packages when package.json is nested inside a larger project

### ISSUE THREAD

**Issue by scooby359** [anish000kumar/easy-npm-support#3]
I have a project that contains dotnet backend controllers and a front end React site, so the project folder structure is split up to manage the files.

In this project, my package.json is nested a few folders in - C:\Source\root\Services\site\site\ClientApp\package.json. . When I open VSCode at the `.\root\` folder, easy-npm shows the correct folder path for my package.json file, but none of the packages are shown.

I've tried directly opening the ClientApp folder in VS Code and that does work as expected. 

Error in the output log:
```
2023-04-12 17:38:48.656 [error] Error: ENOENT: no such file or directory, open 'c:\Source\root\package.json'
```

It appears to be looking for package.json in the root of the opened folder instead of in nested folders

**Comment by anish000kumar** [comment]
Thanks for reporting the bug. Should be resolved in latest release. Feel free to reopen, if it persists.
