### ISSUE TITLE
The extension doesn't find new versions which are available

### ISSUE THREAD

**Issue by alessandro-newzoo** [anish000kumar/easy-npm-support#4]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/47320294/231981507-3dc5e5ad-e25a-4562-852d-4577642b9e57.png">

There's more of these under Dev Dependencies.

Not sure what's causing this, as you can see multiple packages have an update available but it won't show up in your extension. For `Flowbite` it even shows an older version than the one installed.

Also not sure where it's pulling this data from, because even though it shows "No Readme", if I click here, it takes me to the right page on npmjs.com, which shows the correct latest version as well as the readme:

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/47320294/231981970-64f32e6f-6894-4fd7-a578-55f2d2dc256a.png">
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/47320294/231982368-d1badc18-fa07-4050-ab4b-10a719ced8d1.png">

Anything I can do to help debugging this? Does the extension generate  any logs?

`package.json`:
```json
{
  "dependencies": {
    "flowbite": "^1.6.4",
    "@tailwindcss/line-clamp": "^0.4.2",
    "tailwindcss": "^3.2.4"
  },
  "name": "newzoo",
  "version": "1.0.0",
  "main": "gulpfile.js",
  "directories": {
    "lib": "lib"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "stylelint-check": "stylelint-config-prettier-check"
  },
  "devDependencies": {
    "yarn": "^1.22.19",
    "browser-sync": "^2.27.11",
    "eslint-config-gsap": "^3.0.0",
    "gulp": "^4.0.2",
    "gulp-autoprefixer": "^8.0.0",
    "gulp-changed": "^4.0.3",
    "gulp-csso": "^4.0.1",
    "gulp-less": "^5.0.0",
    "gulp-plumber": "^1.2.1",
    "postcss": "^8.4.21",
    "postcss-color-function": "^4.1.0",
    "prettier-plugin-twig-melody": "^0.4.6",
    "autoprefixer": "^10.4.13",
    "cssnano": "^5.1.14",
    "djlint": "^1.19.12",
    "eslint": "^8.31.0",
    "eslint-plugin-html": "^7.1.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jquery": "^1.5.1",
    "eslint-plugin-php-markup": "^6.0.0",
    "gulp-postcss": "^9.0.1",
    "gulp-rename": "^2.0.0",
    "npm-check-updates": "^16.6.2",
    "postcss-less": "^6.0.0",
    "prettier": "^2.8.3",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "stylelint": "^14.16.1",
    "stylelint-config-prettier": "^9.0.5",
    "stylelint-config-recommended": "^9.0.0",
    "stylelint-config-recommended-less": "^1.0.4",
    "stylelint-less": "^1.0.6"
  }
}
```

**Comment by anish000kumar** [comment]
Thanks for reporting the bug. Turns out the data return by API (from https://npms.io/) was not accurate. With latest release (0.2.1) easy-npm uses public API from npms.org, which seems to return correct versions. 

Regarding readme, both APIs do not return readme's for some packages. Not sure what's the reasoning behind it, you can try the public API to debug this at your end, eg. https://registry.npmjs.org/react
However, extension would now  try to fetch the readme from github repo, if API fails to return it, so you should see fewer instances of no readme.

**Comment by alessandro-newzoo** [comment]
@anish000kumar legend, thank you so much!
