### ISSUE TITLE
Doesn't update empty package.json in subdirectory

### ISSUE THREAD

**Issue by dalgleish** [anish000kumar/easy-npm-support#5]
This didn't seem to work for me.
I've got an existing directory structure open in vscode:
```
/
├─ ch1/
│  ├─ index.js
```

In zsh, I create a `package.json`:

```zsh
~/ch1/
npm init -y
```

So now I have
```
/
├─ ch1/
│  ├─ index.js
│  ├─ package.json
```

Then in easy-npm I search for `multiparty` and click save
![image](https://user-images.githubusercontent.com/437422/233455330-8e4edab8-586c-425d-a06e-c4dfd9f1507c.png)

It looks like it works:
![image](https://user-images.githubusercontent.com/437422/233455460-2f28e652-857c-4a57-bb64-627e67151810.png)

But my `package.json` is unchanged, and there is no `node_modules`

## Versions
```
MacOS: Ventura 13.3.1 (22E261)
VSCode: 1.77.3 (Universal)
npm: 9.5.1
```

**Comment by dalgleish** [comment]
Oh I think I see whats going on.

**easy-npm** performed the install in a different directory, not the one I was working in.
It looks like it will allow me to select directories from the blue path selector, if they have a `package.json`.
I guess that makes sense.

**Comment by anish000kumar** [comment]
Hi @dalgleish from the screenshot it seems like you are in a different directory than where you are expecting package to be installed.

Are you expecting installation in .../ch01 folder? Screenshot shows you are in .../ch01/01_08/start

**Comment by anish000kumar** [comment]
A quick note on how default path selection works here. 

By default easy-npm should select the root package.json (if one exists), from the workspace you have open. If you manually switch to a package.json from subdirectory, it'll remember that next time when you come back.

**Comment by dalgleish** [comment]
Thanks @anish000kumar. Maybe I can help by submitting a PR to add details to documentation.

**Comment by anish000kumar** [comment]
Sure, please feel free to.
